CREATE TABLE CLIENTE
(
	ID		INT IDENTITY,
	NOME	VARCHAR(150),
	CPF		VARCHAR(14),
	UF		VARCHAR(2),
	CELULAR	VARCHAR(11),
	PRIMARY KEY (ID)
)
CREATE TABLE FINANCIAMENTO
(
	ID							INT IDENTITY,
	CPF							VARCHAR(14),
	VALOR_FINANCIAMENTO			DECIMAL(12,2),
	VALOR_TOTAL					DECIMAL(12,2),
	TIPO_FINANCIAMENTO			INT,
	PARCELAS					INT,
	DATA_PRIMEIRO_VENCIMENTO	DATETIME,
	DATA_ULTIMO_VENCIMENTO		DATETIME,
	STATUS_FINANCIAMENTO		VARCHAR(30),
	PRIMARY KEY (ID)
)
CREATE TABLE PARCELA
(
	ID					INT IDENTITY,
	ID_FINANCIAMENTO	INT,
	NUMERO_PARCELA		INT,
	VALOR_PARCELA		DECIMAL(12,2),
	DATA_VENCIMENTO		DATETIME,
	DATA_PAGAMENTO		DATETIME,
	PRIMARY KEY (ID)
)


--Listar os primeiros quatro clientes que possuem alguma parcela com mais de cinco dia sem atraso (Data Vencimento maior que data atual E data pagamento nula).
SELECT TOP 4 C.ID,C.NOME,C.CPF,C.UF,C.CELULAR from CLIENTE C
INNER JOIN FINANCIAMENTO F ON C.CPF = F.CPF
INNER JOIN PARCELA P ON F.ID = P.ID_FINANCIAMENTO
WHERE P.DATA_VENCIMENTO > DATEADD(DAY,5,GETDATE())
AND DATA_PAGAMENTO IS NULL
GROUP BY C.ID,C.NOME,C.CPF,C.UF,C.CELULAR

--Listar todos os clientes do estado de SP que possuem mais de 60% das parcelas pagas
declare
@UF varchar(2) = 'SP'

select C.ID,C.NOME,C.CPF,C.UF,C.CELULAR from CLIENTE C
INNER JOIN FINANCIAMENTO F ON C.CPF = F.CPF
WHERE C.UF = @UF
AND C.CPF IN (
SELECT F.CPF FROM FINANCIAMENTO F
INNER JOIN PARCELA P ON F.ID = P.ID_FINANCIAMENTO
WHERE DATA_PAGAMENTO IS NOT NULL
GROUP BY F.CPF,P.ID_FINANCIAMENTO
HAVING CONVERT(DECIMAL(5,2),(COUNT(P.ID_FINANCIAMENTO) / CONVERT(DECIMAL(5,2), (SELECT COUNT(1) FROM PARCELA G WHERE G.ID_FINANCIAMENTO = P.ID_FINANCIAMENTO)))) >= 0.60)
GROUP BY C.ID,C.NOME,C.CPF,C.UF,C.CELULAR


